import type { Organization, CertificateTemplate, Exam, ExamProductCategory } from '@/types.ts';
import { suggestedBooksData } from '@/assets/bookData.ts';

const CERTIFICATE_TEMPLATES: CertificateTemplate[] = [
    { id: 'cert-practice-1', title: 'Medical Coding Proficiency', body: "For successfully demonstrating proficiency in medical coding principles and practices with a final score of <strong>{finalScore}%</strong>. This certifies the holder's competence in the standards required for this certification.", signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cpc', title: 'Certified Professional Coder (CPC)', body: 'For successfully demonstrating proficiency in medical coding principles and practices with a final score of <strong>{finalScore}%</strong>. This certifies competence in the standards required for the CPC credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cca', title: 'Certified Coding Associate (CCA)', body: 'Awarded for exceptional performance and mastery in coding topics, achieving a score of <strong>{finalScore}%</strong>. This signifies a high level of expertise for the CCA credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-billing', title: 'Medical Billing Specialist', body: 'For successfully demonstrating proficiency in medical billing and reimbursement with a final score of <strong>{finalScore}%</strong>. This achievement certifies competence in specialized billing standards.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-ccs', title: 'Certified Coding Specialist (CCS)', body: 'For demonstrating mastery in classifying medical data from patient records with a final score of <strong>{finalScore}%</strong>, as required for the CCS credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-risk', title: 'Certified Risk Adjustment Coder (CRC)', body: 'Awarded for demonstrating expertise in risk adjustment coding with a score of <strong>{finalScore}%</strong>. This signifies competence in linking diagnosis codes to patient conditions for accurate risk assessment.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-icd', title: 'ICD-10-CM Proficiency', body: 'For successfully demonstrating advanced proficiency in the International Classification of Diseases, Tenth Revision, Clinical Modification (ICD-10-CM) with a final score of <strong>{finalScore}%</strong>.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'}
];

const EXAM_PRODUCT_CATEGORIES: ExamProductCategory[] = [
    { id: 'prod-cpc', name: 'CPC', description: 'A test series designed to prepare you for the AAPC CPC (Certified Professional Coder) exam.', practiceExamId: 'exam-cpc-practice', certificationExamId: 'exam-cpc-cert'},
    { id: 'prod-cca', name: 'CCA', description: 'A test series for the AHIMA CCA (Certified Coding Associate) credential.', practiceExamId: 'exam-cca-practice', certificationExamId: 'exam-cca-cert'},
    { id: 'prod-billing', name: 'Medical Billing', description: 'A test series covering the essentials of medical billing and reimbursement.', practiceExamId: 'exam-billing-practice', certificationExamId: 'exam-billing-cert'},
    { id: 'prod-ccs', name: 'CCS', description: 'A test series for the AHIMA CCS (Certified Coding Specialist) credential.', practiceExamId: 'exam-ccs-practice', certificationExamId: 'exam-ccs-cert'},
    { id: 'prod-risk', name: 'Risk Adjustment', description: 'A test series for the Risk Adjustment Coder (CRC) credential.', practiceExamId: 'exam-risk-practice', certificationExamId: 'exam-risk-cert'},
    { id: 'prod-icd', name: 'ICD-10-CM', description: 'A test series for ICD-10-CM coding proficiency.', practiceExamId: 'exam-icd-practice', certificationExamId: 'exam-icd-cert'},
];

const ALL_EXAMS: Omit<Exam, 'recommendedBook'>[] = [
    // Practice Exams
    { id: 'exam-cpc-practice', name: 'CPC Practice Test', description: 'A short practice test to prepare for the CPC certification.', price: 0, productSku: 'exam-cpc-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-cca-practice', name: 'CCA Practice Test', description: 'A short practice test for the Certified Coding Associate exam.', price: 0, productSku: 'exam-cca-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-billing-practice', name: 'Medical Billing Practice Test', description: 'A short practice test for medical billing concepts.', price: 0, productSku: 'exam-billing-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 20, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-ccs-practice', name: 'CCS Practice Test', description: 'Practice for the Certified Coding Specialist exam.', price: 0, productSku: 'exam-ccs-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-risk-practice', name: 'Risk Adjustment Practice Test', description: 'Practice for the Risk Adjustment (CRC) exam.', price: 0, productSku: 'exam-risk-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-icd-practice', name: 'ICD-10-CM Practice Test', description: 'Practice for the ICD-10-CM proficiency exam.', price: 0, productSku: 'exam-icd-practice', numberOfQuestions: 10, passScore: 75, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 20, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    // Certification Exams
    { id: 'exam-cpc-cert', name: 'CPC Certification Exam', description: 'Full certification exam for Certified Professional Coder.', price: 150, regularPrice: 150, productSku: 'exam-cpc-cert', productSlug: 'cpc-certification-exam-preparation', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-cpc', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-cpc-guide'},
    { id: 'exam-cca-cert', name: 'CCA Certification Exam', description: 'Full certification exam for Certified Coding Associate.', price: 120, regularPrice: 120, productSku: 'exam-cca-cert', productSlug: 'cca-certification-exam-preparation', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-cca', isPractice: false, durationMinutes: 180, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-step-by-step'},
    { id: 'exam-ccs-cert', name: 'CCS Certification Exam', description: 'Full certification exam for Certified Coding Specialist.', price: 160, regularPrice: 160, productSku: 'exam-ccs-cert', productSlug: 'ccs-certification-exam-preparation', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-ccs', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-icd10-cm'},
    { id: 'exam-billing-cert', name: 'Medical Billing Certification Exam', description: 'Comprehensive exam covering medical billing and reimbursement.', price: 100, regularPrice: 100, productSku: 'exam-billing-cert', productSlug: 'medical-billing-certification-exam-preparation', numberOfQuestions: 100, passScore: 75, certificateTemplateId: 'cert-billing', isPractice: false, durationMinutes: 150, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-medical-billing'},
    { id: 'exam-risk-cert', name: 'Risk Adjustment (CRC) Certification Exam', description: 'Exam for Certified Risk Adjustment Coder.', price: 150, regularPrice: 150, productSku: 'exam-risk-cert', productSlug: 'risk-adjustment-crc-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-risk', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-risk-adjustment'},
    { id: 'exam-icd-cert', name: 'ICD-10-CM Certification Exam', description: 'Proficiency exam for ICD-10-CM coding.', price: 90, regularPrice: 90, productSku: 'exam-icd-cert', productSlug: 'icd-10-cm-certification-exam-preparation', numberOfQuestions: 100, passScore: 75, certificateTemplateId: 'cert-icd', isPractice: false, durationMinutes: 120, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-icd10-cm'}
];


export const appData: Organization[] = [
    {
        id: 'org-mco',
        name: 'Medical Coding Online',
        website: 'www.coding-online.net',
        logo: '', // Logo is handled by logo.ts
        exams: ALL_EXAMS as Exam[],
        examProductCategories: EXAM_PRODUCT_CATEGORIES,
        certificateTemplates: CERTIFICATE_TEMPLATES,
        suggestedBooks: suggestedBooksData,
    }
];