import type { Organization, CertificateTemplate, Exam, ExamProductCategory } from '../types.ts';
import { suggestedBooksData } from './bookData.ts';

const CERTIFICATE_TEMPLATES: CertificateTemplate[] = [
    { id: 'cert-practice-1', title: 'Medical Coding Proficiency', body: "For successfully demonstrating proficiency in medical coding principles and practices with a final score of <strong>{finalScore}%</strong>. This certifies the holder's competence in the standards required for this certification.", signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cpc', title: 'Certified Professional Coder (CPC)', body: 'For successfully demonstrating proficiency in medical coding principles and practices with a final score of <strong>{finalScore}%</strong>. This certifies competence in the standards required for the CPC credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cca', title: 'Certified Coding Associate (CCA)', body: 'Awarded for exceptional performance and mastery in coding topics, achieving a score of <strong>{finalScore}%</strong>. This signifies a high level of expertise for the CCA credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-billing', title: 'Medical Billing Specialist', body: 'For successfully demonstrating proficiency in medical billing and reimbursement with a final score of <strong>{finalScore}%</strong>. This achievement certifies competence in specialized billing standards.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-ccs', title: 'Certified Coding Specialist (CCS)', body: 'For demonstrating mastery in classifying medical data from patient records with a final score of <strong>{finalScore}%</strong>, as required for the CCS credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-risk', title: 'Risk Adjustment Coding Proficiency', body: 'Awarded for demonstrating expertise in risk adjustment coding with a score of <strong>{finalScore}%</strong>. This signifies competence in linking diagnosis codes to patient conditions for accurate risk assessment.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-icd', title: 'ICD-10-CM Proficiency', body: 'For successfully demonstrating advanced proficiency in the International Classification of Diseases, Tenth Revision, Clinical Modification (ICD-10-CM) with a final score of <strong>{finalScore}%</strong>.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cpb', title: 'Certified Professional Biller (CPB)', body: 'For successfully demonstrating proficiency in medical billing with a final score of <strong>{finalScore}%</strong>. This certifies competence in the standards required for the CPB credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-crc', title: 'Certified Risk Adjustment Coder (CRC)', body: 'Awarded for demonstrating expertise in risk adjustment coding with a score of <strong>{finalScore}%</strong>. This signifies competence for the CRC credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cpma', title: 'Certified Professional Medical Auditor (CPMA)', body: 'For demonstrating mastery in medical auditing and compliance with a final score of <strong>{finalScore}%</strong>, as required for the CPMA credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-coc', title: 'Certified Outpatient Coder (COC)', body: 'For successfully demonstrating proficiency in outpatient and physician-based coding with a final score of <strong>{finalScore}%</strong>. This certifies competence in the standards required for the COC credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cic', title: 'Certified Inpatient Coder (CIC)', body: 'Awarded for demonstrating expertise in inpatient hospital coding with a score of <strong>{finalScore}%</strong>. This signifies a high level of expertise for the CIC credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-mta', title: 'Medical Terminology & Anatomy Proficiency', body: 'For successfully demonstrating advanced proficiency in Medical Terminology and Anatomy with a final score of <strong>{finalScore}%</strong>.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'}
];

const EXAM_PRODUCT_CATEGORIES: ExamProductCategory[] = [
    { id: 'prod-cpc', name: 'CPC', description: 'A test series designed to prepare you for the AAPC CPC (Certified Professional Coder) exam.', practiceExamId: 'exam-cpc-practice', certificationExamId: 'exam-cpc-cert'},
    { id: 'prod-cca', name: 'CCA', description: 'A test series for the AHIMA CCA (Certified Coding Associate) credential.', practiceExamId: 'exam-cca-practice', certificationExamId: 'exam-cca-cert'},
    { id: 'prod-billing', name: 'Medical Billing', description: 'A test series covering the essentials of medical billing and reimbursement.', practiceExamId: 'exam-billing-practice', certificationExamId: 'exam-billing-cert'},
    { id: 'prod-ccs', name: 'CCS', description: 'A test series for the AHIMA CCS (Certified Coding Specialist) credential.', practiceExamId: 'exam-ccs-practice', certificationExamId: 'exam-ccs-cert'},
    { id: 'prod-risk', name: 'Risk Adjustment', description: 'A test series for Risk Adjustment coding proficiency.', practiceExamId: 'exam-risk-practice', certificationExamId: 'exam-risk-cert'},
    { id: 'prod-icd', name: 'ICD-10-CM', description: 'A test series for ICD-10-CM coding proficiency.', practiceExamId: 'exam-icd-practice', certificationExamId: 'exam-icd-cert'},
    { id: 'prod-cpb', name: 'CPB', description: 'A test series for the AAPC CPB (Certified Professional Biller) credential.', practiceExamId: 'exam-cpb-practice', certificationExamId: 'exam-cpb-cert'},
    { id: 'prod-crc', name: 'CRC', description: 'A test series for the AAPC CRC (Certified Risk Adjustment Coder) credential.', practiceExamId: 'exam-crc-practice', certificationExamId: 'exam-crc-cert'},
    { id: 'prod-cpma', name: 'CPMA', description: 'A test series for the AAPC CPMA (Certified Professional Medical Auditor) credential.', practiceExamId: 'exam-cpma-practice', certificationExamId: 'exam-cpma-cert'},
    { id: 'prod-coc', name: 'COC', description: 'A test series for the AAPC COC (Certified Outpatient Coder) credential.', practiceExamId: 'exam-coc-practice', certificationExamId: 'exam-coc-cert'},
    { id: 'prod-cic', name: 'CIC', description: 'A test series for the AAPC CIC (Certified Inpatient Coder) credential.', practiceExamId: 'exam-cic-practice', certificationExamId: 'exam-cic-cert'},
    { id: 'prod-mta', name: 'MTA', description: 'A test series for Medical Terminology & Anatomy proficiency.', practiceExamId: 'exam-mta-practice', certificationExamId: 'exam-mta-cert'},
];

const ALL_EXAMS: Omit<Exam, 'recommendedBook'>[] = [
    // Practice Exams (12)
    { id: 'exam-cpc-practice', name: 'CPC Free Practice', description: 'A short practice test to prepare for the CPC certification.', price: 0, productSku: 'exam-cpc-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-cca-practice', name: 'CCA Free Practice', description: 'A short practice test for the Certified Coding Associate exam.', price: 0, productSku: 'exam-cca-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-billing-practice', name: 'Medical Billing Free Practice', description: 'A short practice test for medical billing concepts.', price: 0, productSku: 'exam-billing-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 20, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-ccs-practice', name: 'CCS Free Practice', description: 'Practice for the Certified Coding Specialist exam.', price: 0, productSku: 'exam-ccs-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-risk-practice', name: 'Risk Adjustment Free Practice', description: 'Practice for Risk Adjustment coding proficiency.', price: 0, productSku: 'exam-risk-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-icd-practice', name: 'ICD-10-CM Free Practice', description: 'Practice for the ICD-10-CM proficiency exam.', price: 0, productSku: 'exam-icd-practice', numberOfQuestions: 10, passScore: 75, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 20, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-cpb-practice', name: 'CPB Free Practice', description: 'Practice for the Certified Professional Biller exam.', price: 0, productSku: 'exam-cpb-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-crc-practice', name: 'CRC Free Practice', description: 'Practice for the Certified Risk Adjustment Coder exam.', price: 0, productSku: 'exam-crc-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-cpma-practice', name: 'CPMA Free Practice', description: 'Practice for the Certified Professional Medical Auditor exam.', price: 0, productSku: 'exam-cpma-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-coc-practice', name: 'COC Free Practice', description: 'Practice for the Certified Outpatient Coder exam.', price: 0, productSku: 'exam-coc-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-cic-practice', name: 'CIC Free Practice', description: 'Practice for the Certified Inpatient Coder exam.', price: 0, productSku: 'exam-cic-practice', numberOfQuestions: 10, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 25, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-mta-practice', name: 'Medical Terminology & Anatomy Free Practice', description: 'Practice for the Medical Terminology & Anatomy exam.', price: 0, productSku: 'exam-mta-practice', numberOfQuestions: 10, passScore: 75, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 20, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    
    // Certification Exams (12)
    { id: 'exam-cpc-cert', name: 'CPC Certification Exam', description: 'Full certification exam for Certified Professional Coder.', price: 150, regularPrice: 150, productSku: 'exam-cpc-cert', productSlug: 'cpc-certification-exam-preparation', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-cpc', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-cpc-guide'},
    { id: 'exam-cca-cert', name: 'CCA Certification Exam', description: 'Full certification exam for Certified Coding Associate.', price: 120, regularPrice: 120, productSku: 'exam-cca-cert', productSlug: 'cca-certification-exam-preparation', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-cca', isPractice: false, durationMinutes: 180, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-step-by-step'},
    { id: 'exam-ccs-cert', name: 'CCS Certification Exam', description: 'Full certification exam for Certified Coding Specialist.', price: 160, regularPrice: 160, productSku: 'exam-ccs-cert', productSlug: 'ccs-certification-exam-preparation', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-ccs', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-icd10-cm'},
    { id: 'exam-billing-cert', name: 'Medical Billing Certification Exam', description: 'Comprehensive exam covering medical billing and reimbursement.', price: 100, regularPrice: 100, productSku: 'exam-billing-cert', productSlug: 'medical-billing-certification-exam-preparation', numberOfQuestions: 100, passScore: 75, certificateTemplateId: 'cert-billing', isPractice: false, durationMinutes: 150, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-medical-billing'},
    { id: 'exam-risk-cert', name: 'Risk Adjustment Certification Exam', description: 'Exam for Risk Adjustment Coding.', price: 150, regularPrice: 150, productSku: 'exam-risk-cert', productSlug: 'risk-adjustment-coding-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-risk', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-risk-adjustment'},
    { id: 'exam-icd-cert', name: 'ICD-10-CM Certification Exam', description: 'Proficiency exam for ICD-10-CM coding.', price: 90, regularPrice: 90, productSku: 'exam-icd-cert', productSlug: 'icd-10-cm-certification-exam-preparation', numberOfQuestions: 100, passScore: 75, certificateTemplateId: 'cert-icd', isPractice: false, durationMinutes: 120, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing', recommendedBookId: 'book-icd10-cm'},
    { id: 'exam-cpb-cert', name: 'CPB Certification Exam', description: 'Full certification exam for Certified Professional Biller.', price: 150, regularPrice: 150, productSku: 'exam-cpb-cert', productSlug: 'cpb-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-cpb', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-crc-cert', name: 'CRC Certification Exam', description: 'Full certification exam for Certified Risk Adjustment Coder.', price: 150, regularPrice: 150, productSku: 'exam-crc-cert', productSlug: 'crc-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-crc', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-cpma-cert', name: 'CPMA Certification Exam', description: 'Full certification exam for Certified Professional Medical Auditor.', price: 150, regularPrice: 150, productSku: 'exam-cpma-cert', productSlug: 'cpma-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-cpma', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-coc-cert', name: 'COC Certification Exam', description: 'Full certification exam for Certified Outpatient Coder.', price: 150, regularPrice: 150, productSku: 'exam-coc-cert', productSlug: 'coc-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-coc', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-cic-cert', name: 'CIC Certification Exam', description: 'Full certification exam for Certified Inpatient Coder.', price: 160, regularPrice: 160, productSku: 'exam-cic-cert', productSlug: 'cic-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-cic', isPractice: false, durationMinutes: 240, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'},
    { id: 'exam-mta-cert', name: 'Medical Terminology & Anatomy Certification Exam', description: 'Proficiency exam for Medical Terminology & Anatomy.', price: 90, regularPrice: 90, productSku: 'exam-mta-cert', productSlug: 'medical-terminology-anatomy-certification-exam', numberOfQuestions: 100, passScore: 75, certificateTemplateId: 'cert-mta', isPractice: false, durationMinutes: 120, questionSourceUrl: 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing'}
];


export const appData: Organization[] = [
    {
        id: 'org-mco',
        name: 'Medical Coding Online',
        website: 'www.coding-online.net',
        logo: '', // Logo is handled by logo.ts
        exams: ALL_EXAMS as Exam[],
        examProductCategories: EXAM_PRODUCT_CATEGORIES,
        certificateTemplates: CERTIFICATE_TEMPLATES,
        suggestedBooks: suggestedBooksData,
    }
];