import type { Organization, CertificateTemplate, Exam, ExamProductCategory } from '../types.ts';
import { suggestedBooksData } from './bookData.ts';

const CERTIFICATE_TEMPLATES: CertificateTemplate[] = [
    { id: 'cert-practice-1', title: 'Medical Coding Proficiency', body: "For successfully demonstrating proficiency in medical coding principles and practices with a final score of <strong>{finalScore}%</strong>. This certifies the holder's competence in the standards required for this certification.", signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cpc', title: 'Certified Professional Coder (CPC)', body: 'For successfully demonstrating proficiency in medical coding principles and practices with a final score of <strong>{finalScore}%</strong>. This certifies competence in the standards required for the CPC credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cca', title: 'Certified Coding Associate (CCA)', body: 'Awarded for exceptional performance and mastery in coding topics, achieving a score of <strong>{finalScore}%</strong>. This signifies a high level of expertise for the CCA credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-billing', title: 'Medical Billing Specialist', body: 'For successfully demonstrating proficiency in medical billing and reimbursement with a final score of <strong>{finalScore}%</strong>. This achievement certifies competence in specialized billing standards.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-ccs', title: 'Certified Coding Specialist (CCS)', body: 'For demonstrating mastery in classifying medical data from patient records with a final score of <strong>{finalScore}%</strong>, as required for the CCS credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-risk', title: 'Risk Adjustment Coding Proficiency', body: 'Awarded for demonstrating expertise in risk adjustment coding with a score of <strong>{finalScore}%</strong>. This signifies competence in linking diagnosis codes to patient conditions for accurate risk assessment.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-icd', title: 'ICD-10-CM Proficiency', body: 'For successfully demonstrating advanced proficiency in the International Classification of Diseases, Tenth Revision, Clinical Modification (ICD-10-CM) with a final score of <strong>{finalScore}%</strong>.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cpb', title: 'Certified Professional Biller (CPB)', body: 'For successfully demonstrating proficiency in medical billing with a final score of <strong>{finalScore}%</strong>. This certifies competence in the standards required for the CPB credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-crc', title: 'Certified Risk Adjustment Coder (CRC)', body: 'Awarded for demonstrating expertise in risk adjustment coding with a score of <strong>{finalScore}%</strong>. This signifies competence for the CRC credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cpma', title: 'Certified Professional Medical Auditor (CPMA)', body: 'For demonstrating mastery in medical auditing and compliance with a final score of <strong>{finalScore}%</strong>, as required for the CPMA credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-coc', title: 'Certified Outpatient Coder (COC)', body: 'For successfully demonstrating proficiency in outpatient and physician-based coding with a final score of <strong>{finalScore}%</strong>. This certifies competence in the standards required for the COC credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-cic', title: 'Certified Inpatient Coder (CIC)', body: 'Awarded for demonstrating expertise in inpatient hospital coding with a score of <strong>{finalScore}%</strong>. This signifies a high level of expertise for the CIC credential.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-mta', title: 'Medical Terminology & Anatomy Proficiency', body: 'For successfully demonstrating advanced proficiency in Medical Terminology and Anatomy with a final score of <strong>{finalScore}%</strong>.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-ap', title: 'Anatomy & Physiology Proficiency', body: 'For successfully demonstrating proficiency in Anatomy & Physiology principles with a final score of <strong>{finalScore}%</strong>.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-em', title: 'Evaluation & Management Coding Proficiency', body: 'For successfully demonstrating proficiency in E/M coding with a final score of <strong>{finalScore}%</strong>.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-rcm', title: 'Revenue Cycle Management Proficiency', body: 'For successfully demonstrating proficiency in Revenue Cycle Management with a final score of <strong>{finalScore}%</strong>.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-hi', title: 'Health Informatics Proficiency', body: 'For successfully demonstrating proficiency in Health Informatics with a final score of <strong>{finalScore}%</strong>.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
    { id: 'cert-mcf', title: 'Medical Coding Fundamentals Proficiency', body: 'For successfully demonstrating proficiency in foundational medical coding principles with a final score of <strong>{finalScore}%</strong>.', signature1Name: 'Dr. Amelia Reed', signature1Title: 'Program Director', signature2Name: 'B. Manoj', signature2Title: 'Chief Instructor'},
];

const MASTER_QUESTION_SHEET = 'https://docs.google.com/spreadsheets/d/10QGeiupsw6KtW9613v1yj03SYtzf3rDCEu-hbgQUwgs/edit?usp=sharing';

const EXAM_PRODUCT_CATEGORIES: ExamProductCategory[] = [
    { id: 'prod-cpc', name: 'CPC', description: 'A test series designed to prepare you for the AAPC CPC (Certified Professional Coder) exam.', practiceExamId: 'exam-cpc-practice', certificationExamId: 'exam-cpc-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-cca', name: 'CCA', description: 'A test series for the AHIMA CCA (Certified Coding Associate) credential.', practiceExamId: 'exam-cca-practice', certificationExamId: 'exam-cca-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-billing', name: 'Medical Billing', description: 'A test series covering the essentials of medical billing and reimbursement.', practiceExamId: 'exam-billing-practice', certificationExamId: 'exam-billing-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-ccs', name: 'CCS', description: 'A test series for the AHIMA CCS (Certified Coding Specialist) credential.', practiceExamId: 'exam-ccs-practice', certificationExamId: 'exam-ccs-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-risk', name: 'Risk Adjustment', description: 'A test series for Risk Adjustment coding proficiency.', practiceExamId: 'exam-risk-practice', certificationExamId: 'exam-risk-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-icd', name: 'ICD-10-CM', description: 'A test series for ICD-10-CM coding proficiency.', practiceExamId: 'exam-icd-practice', certificationExamId: 'exam-icd-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-cpb', name: 'CPB', description: 'A test series for the AAPC CPB (Certified Professional Biller) credential.', practiceExamId: 'exam-cpb-practice', certificationExamId: 'exam-cpb-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-crc', name: 'CRC', description: 'A test series for the AAPC CRC (Certified Risk Adjustment Coder) credential.', practiceExamId: 'exam-crc-practice', certificationExamId: 'exam-crc-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-cpma', name: 'CPMA', description: 'A test series for the AAPC CPMA (Certified Professional Medical Auditor) credential.', practiceExamId: 'exam-cpma-practice', certificationExamId: 'exam-cpma-cert', questionSourceUrl: 'https://docs.google.com/spreadsheets/d/1dpXSZlD7Kl8OgAv6ECPbQvygozwE7J3ChpjlZfndjSA/edit?usp=sharing'},
    { id: 'prod-coc', name: 'COC', description: 'A test series for the AAPC COC (Certified Outpatient Coder) credential.', practiceExamId: 'exam-coc-practice', certificationExamId: 'exam-coc-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-cic', name: 'CIC', description: 'A test series for the AAPC CIC (Certified Inpatient Coder) credential.', practiceExamId: 'exam-cic-practice', certificationExamId: 'exam-cic-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-mta', name: 'MTA', description: 'A test series for Medical Terminology & Anatomy proficiency.', practiceExamId: 'exam-mta-practice', certificationExamId: 'exam-mta-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-ap', name: 'A&P', description: 'A test series for Anatomy & Physiology proficiency.', practiceExamId: 'exam-ap-practice', certificationExamId: 'exam-ap-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-em', name: 'E/M', description: 'A test series for Evaluation & Management coding proficiency.', practiceExamId: 'exam-em-practice', certificationExamId: 'exam-em-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-rcm', name: 'RCM', description: 'A test series for Revenue Cycle Management proficiency.', practiceExamId: 'exam-rcm-practice', certificationExamId: 'exam-rcm-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-hi', name: 'Health Informatics', description: 'A test series for Health Informatics proficiency.', practiceExamId: 'exam-hi-practice', certificationExamId: 'exam-hi-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
    { id: 'prod-mcf', name: 'MCF', description: 'A foundational test series covering core medical coding principles.', practiceExamId: 'exam-mcf-practice', certificationExamId: 'exam-mcf-cert', questionSourceUrl: MASTER_QUESTION_SHEET},
];

const ALL_EXAMS: Omit<Exam, 'recommendedBook' | 'questionSourceUrl'>[] = [
    // CPC Exam Program
    { id: 'exam-cpc-practice', name: 'CPC Free Practice', description: 'A practice test to prepare for the CPC certification.', price: 0, productSku: 'exam-cpc-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-cpc-cert', name: 'CPC Certification Exam', description: 'This comprehensive exam tests your mastery of CPT, HCPCS Level II, and ICD-10-CM coding for physician services. Prove your readiness for the official AAPC CPC credential.', price: 1, regularPrice: 49.99, productSku: 'exam-cpc-cert', productSlug: 'cpc-certification-exam-preparation', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-cpc', isPractice: false, durationMinutes: 240, recommendedBookId: 'book-cpc-guide'},
    // CCA Exam Program
    { id: 'exam-cca-practice', name: 'CCA Free Practice', description: 'A practice test for the Certified Coding Associate exam.', price: 0, productSku: 'exam-cca-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-cca-cert', name: 'CCA Certification Exam', description: 'Demonstrate your competency in coding patient data across all settings, including hospitals and physician practices. A crucial step towards achieving your AHIMA CCA certification.', price: 1, regularPrice: 49.99, productSku: 'exam-cca-cert', productSlug: 'cca-certification-exam-preparation', numberOfQuestions: 115, passScore: 70, certificateTemplateId: 'cert-cca', isPractice: false, durationMinutes: 120, recommendedBookId: 'book-step-by-step'},
    // Medical Billing Program
    { id: 'exam-billing-practice', name: 'Medical Billing Free Practice', description: 'A practice test for medical billing concepts.', price: 0, productSku: 'exam-billing-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-billing-cert', name: 'Medical Billing Certification', description: 'Validate your expertise in the entire medical billing process, from patient registration and claim submission to payment posting and collections. Ideal for aspiring billing specialists.', price: 1, regularPrice: 49.99, productSku: 'exam-billing-cert', productSlug: 'medical-billing-certification-exam-preparation', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-billing', isPractice: false, durationMinutes: 180, recommendedBookId: 'book-medical-billing'},
    // CCS Exam Program
    { id: 'exam-ccs-practice', name: 'CCS Free Practice', description: 'Practice for the Certified Coding Specialist exam.', price: 0, productSku: 'exam-ccs-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-ccs-cert', name: 'CCS Certification Exam', description: 'Showcase your advanced skills in classifying medical data from patient records, particularly in hospital settings. Prepares you for the rigorous AHIMA CCS credential.', price: 1, regularPrice: 49.99, productSku: 'exam-ccs-cert', productSlug: 'ccs-certification-exam-preparation', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-ccs', isPractice: false, durationMinutes: 240, recommendedBookId: 'book-icd10-pcs'},
    // Risk Adjustment Program
    { id: 'exam-risk-practice', name: 'Risk Adjustment Free Practice', description: 'Practice for Risk Adjustment coding proficiency.', price: 0, productSku: 'exam-risk-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-risk-cert', name: 'Risk Adjustment Certification', description: 'Master the principles of risk adjustment coding. This exam evaluates your ability to accurately assign ICD-10-CM codes to reflect patient health status for proper reimbursement.', price: 1, regularPrice: 49.99, productSku: 'exam-risk-cert', productSlug: 'risk-adjustment-certification-exam-preparation', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-risk', isPractice: false, durationMinutes: 180, recommendedBookId: 'book-risk-adjustment'},
    // ICD-10-CM Program
    { id: 'exam-icd-practice', name: 'ICD-10-CM Free Practice', description: 'Practice your ICD-10-CM coding skills.', price: 0, productSku: 'exam-icd-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-icd-cert', name: 'ICD-10-CM Proficiency Exam', description: 'An in-depth assessment of your ability to accurately use the ICD-10-CM code set for diagnosis coding across various healthcare settings. Perfect for validating your specialized skills.', price: 1, regularPrice: 49.99, productSku: 'exam-icd-cert', productSlug: 'icd-10-cm-proficiency-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-icd', isPractice: false, durationMinutes: 180, recommendedBookId: 'book-icd10-cm'},
    // CPB Exam Program
    { id: 'exam-cpb-practice', name: 'CPB Free Practice', description: 'Practice for the Certified Professional Biller exam.', price: 0, productSku: 'exam-cpb-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-cpb-cert', name: 'CPB Certification Exam', description: 'Prove your proficiency in all aspects of medical billing, including claim processing, denials management, and compliance. Aligns with the AAPC CPB certification standards.', price: 1, regularPrice: 49.99, productSku: 'exam-cpb-cert', productSlug: 'cpb-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-cpb', isPractice: false, durationMinutes: 240, recommendedBookId: 'book-medical-billing'},
    // CRC Exam Program
    { id: 'exam-crc-practice', name: 'CRC Free Practice', description: 'Practice for the Certified Risk Adjustment Coder exam.', price: 0, productSku: 'exam-crc-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-crc-cert', name: 'CRC Certification Exam', description: 'This exam validates your expertise in risk adjustment (HCC) models. It tests your ability to link diagnoses to chronic conditions for accurate risk score calculation.', price: 1, regularPrice: 49.99, productSku: 'exam-crc-cert', productSlug: 'crc-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-crc', isPractice: false, durationMinutes: 240, recommendedBookId: 'book-risk-adjustment'},
    // CPMA Exam Program
    { id: 'exam-cpma-practice', name: 'CPMA Free Practice', description: 'Practice for the Certified Professional Medical Auditor exam.', price: 0, productSku: 'exam-cpma-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-cpma-cert', name: 'CPMA Certification Exam', description: 'Demonstrate your skills in medical auditing and compliance. This exam covers documentation guidelines, coding standards, and risk analysis for the AAPC CPMA credential.', price: 1, regularPrice: 49.99, productSku: 'exam-cpma-cert', productSlug: 'cpma-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-cpma', isPractice: false, durationMinutes: 240, recommendedBookId: 'book-auditing'},
    // COC Exam Program
    { id: 'exam-coc-practice', name: 'COC Free Practice', description: 'Practice for the Certified Outpatient Coder exam.', price: 0, productSku: 'exam-coc-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-coc-cert', name: 'COC Certification Exam', description: 'Test your knowledge of outpatient coding, including CPT, ICD-10-CM, and HCPCS Level II, as it applies to hospital outpatient departments and ambulatory surgery centers.', price: 1, regularPrice: 49.99, productSku: 'exam-coc-cert', productSlug: 'coc-certification-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-coc', isPractice: false, durationMinutes: 240, recommendedBookId: 'book-outpatient'},
    // CIC Exam Program
    { id: 'exam-cic-practice', name: 'CIC Free Practice', description: 'Practice for the Certified Inpatient Coder exam.', price: 0, productSku: 'exam-cic-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-cic-cert', name: 'CIC Certification Exam', description: 'This exam assesses your ability to assign accurate codes for diagnoses and procedures in the inpatient hospital setting, covering ICD-10-CM and ICD-10-PCS.', price: 1, regularPrice: 49.99, productSku: 'exam-cic-cert', productSlug: 'cic-certification-exam', numberOfQuestions: 75, passScore: 70, certificateTemplateId: 'cert-cic', isPractice: false, durationMinutes: 150, recommendedBookId: 'book-icd10-pcs'},
    // MTA Program
    { id: 'exam-mta-practice', name: 'Medical Terminology & Anatomy Free Practice', description: 'Test your knowledge of medical terminology and anatomy.', price: 0, productSku: 'exam-mta-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-mta-cert', name: 'Medical Terminology & Anatomy Proficiency', description: 'A foundational exam to certify your understanding of the medical language and human body systems that are essential for accurate coding.', price: 1, regularPrice: 49.99, productSku: 'exam-mta-cert', productSlug: 'mta-proficiency-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-mta', isPractice: false, durationMinutes: 120, recommendedBookId: 'book-terminology-dummies'},
    // Anatomy & Physiology Program
    { id: 'exam-ap-practice', name: 'Anatomy & Physiology Free Practice', description: 'Practice your Anatomy & Physiology knowledge.', price: 0, productSku: 'exam-ap-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-ap-cert', name: 'Anatomy & Physiology Proficiency', description: 'Validate your comprehensive knowledge of human anatomy and physiology, a core competency for any medical coding or healthcare professional.', price: 1, regularPrice: 49.99, productSku: 'exam-ap-cert', productSlug: 'ap-proficiency-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-ap', isPractice: false, durationMinutes: 120, recommendedBookId: 'book-anatomy-physiology'},
    // E/M Coding Program
    { id: 'exam-em-practice', name: 'E/M Coding Free Practice', description: 'Practice your Evaluation & Management coding skills.', price: 0, productSku: 'exam-em-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-em-cert', name: 'Evaluation & Management Proficiency', description: 'Demonstrate your expertise in the complex world of Evaluation and Management (E/M) coding, including the latest guidelines for office visits and other services.', price: 1, regularPrice: 49.99, productSku: 'exam-em-cert', productSlug: 'em-proficiency-exam', numberOfQuestions: 50, passScore: 70, certificateTemplateId: 'cert-em', isPractice: false, durationMinutes: 90, recommendedBookId: 'book-em-coding'},
    // Revenue Cycle Management Program
    { id: 'exam-rcm-practice', name: 'RCM Free Practice', description: 'Practice your Revenue Cycle Management knowledge.', price: 0, productSku: 'exam-rcm-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-rcm-cert', name: 'Revenue Cycle Management Proficiency', description: 'This comprehensive exam covers all stages of the healthcare revenue cycle, from patient access and charge capture to claims management and analytics.', price: 1, regularPrice: 49.99, productSku: 'exam-rcm-cert', productSlug: 'rcm-proficiency-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-rcm', isPractice: false, durationMinutes: 120, recommendedBookId: 'book-revenue-cycle'},
    // Health Informatics Program
    { id: 'exam-hi-practice', name: 'Health Informatics Free Practice', description: 'Practice your Health Informatics knowledge.', price: 0, productSku: 'exam-hi-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-hi-cert', name: 'Health Informatics Proficiency', description: 'Test your understanding of health informatics principles, including data standards, electronic health records (EHRs), and data analytics in healthcare.', price: 1, regularPrice: 49.99, productSku: 'exam-hi-cert', productSlug: 'hi-proficiency-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-hi', isPractice: false, durationMinutes: 120, recommendedBookId: 'book-informatics'},
    // Medical Coding Fundamentals Program
    { id: 'exam-mcf-practice', name: 'Medical Coding Fundamentals Practice', description: 'Test your foundational medical coding knowledge.', price: 0, productSku: 'exam-mcf-practice', numberOfQuestions: 25, passScore: 70, certificateTemplateId: 'cert-practice-1', isPractice: true, durationMinutes: 60},
    { id: 'exam-mcf-cert', name: 'Medical Coding Fundamentals Proficiency', description: 'Establish your grasp of the essential principles of medical coding. This exam covers foundational concepts that are crucial for a successful career in the field.', price: 1, regularPrice: 49.99, productSku: 'exam-mcf-cert', productSlug: 'mcf-proficiency-exam', numberOfQuestions: 100, passScore: 70, certificateTemplateId: 'cert-mcf', isPractice: false, durationMinutes: 120, recommendedBookId: 'book-step-by-step'},
];

export const appData: Organization[] = [
    {
        id: 'org-mco',
        name: 'Medical Coding Online',
        website: 'coding-online.net',
        logo: '/logo.png',
        exams: ALL_EXAMS as Exam[],
        examProductCategories: EXAM_PRODUCT_CATEGORIES,
        certificateTemplates: CERTIFICATE_TEMPLATES,
        suggestedBooks: suggestedBooksData,
    }
];
