import type { RecommendedBook } from '../types.ts';

export const suggestedBooksData: RecommendedBook[] = [
    // Existing 6 books
    { id: 'book-cpc-guide', title: 'Official CPC® Certification Study Guide', description: "AAPC's official CPC exam study guide — anatomy, medical terminology, ICD-10-CM, CPT, HCPCS, practice questions and exam tips.", affiliateLinks: { 'com': 'https://www.amazon.com/dp/1635278910?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1635278910?tag=httpcodingonl-21', 'ae': ''}},
    { id: 'book-icd10-cm', title: "Buck's ICD-10-CM for Physicians 2026", description: "Physician-focused ICD-10-CM code manual with full-color illustrations, Netter's Anatomy, and detailed guidelines.", affiliateLinks: { 'com': 'https://www.amazon.com/dp/0443380783?tag=mykada-20', 'in': 'https://www.amazon.in/dp/0443380783?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/0443380783?tag=medical0f1-21'}},
    { id: 'book-cpt-pro', title: 'AMA CPT® Professional 2026', description: 'The official Current Procedural Terminology (CPT) codebook from the American Medical Association, essential for every coder.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1640163354?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1640163354?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1640163354?tag=medical0f1-21'}},
    { id: 'book-hcpcs-level2', title: 'HCPCS Level II Professional 2026', description: 'Comprehensive guide for HCPCS Level II codes used for supplies, equipment, and drugs administered by physicians.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1622029947?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1622029947?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1622029947?tag=medical0f1-21'}},
    { id: 'book-medical-billing', title: 'Medical Billing & Coding For Dummies', description: 'An easy-to-understand guide covering the basics of medical billing and coding, perfect for beginners.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1119750393?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1119750393?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1119750393?tag=medical0f1-21'}},
    { id: 'book-step-by-step', title: 'Step-by-Step Medical Coding, 2024 Edition', description: 'This guide provides a solid foundation with a practical approach to mastering medical coding concepts and applications.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/0323930872?tag=mykada-20', 'in': 'https://www.amazon.in/dp/0323930872?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/0323930872?tag=medical0f1-21'}},
    // 14 new books
    { id: 'book-anatomy-physiology', title: 'Anatomy & Physiology for Coders', description: 'A focused guide on anatomy and physiology tailored specifically for medical coding professionals to improve accuracy.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/0323796582?tag=mykada-20', 'in': 'https://www.amazon.in/dp/0323796582?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/0323796582?tag=medical0f1-21'}},
    { id: 'book-terminology-dummies', title: 'Medical Terminology For Dummies', description: 'Break down complex medical terms into simple, understandable parts. An essential resource for new coders.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1119850533?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1119850533?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1119850533?tag=medical0f1-21'}},
    { id: 'book-icd10-pcs', title: 'ICD-10-PCS: An Applied Approach', description: 'Master inpatient procedural coding with this comprehensive guide to the ICD-10-PCS system, full of exercises.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1584268910?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1584268910?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1584268910?tag=medical0f1-21'}},
    { id: 'book-risk-adjustment', title: 'Risk Adjustment Documentation & Coding', description: 'A deep dive into risk adjustment models (HCC) and the documentation required for accurate coding and reimbursement.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1622028290?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1622028290?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1622028290?tag=medical0f1-21'}},
    { id: 'book-auditing', title: 'The Medical Auditing Handbook', description: 'Learn the principles of medical coding auditing to ensure compliance, accuracy, and prevent fraud and abuse.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1622028258?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1622028258?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1622028258?tag=medical0f1-21'}},
    { id: 'book-compliance', title: 'Healthcare Compliance Professional\'s Manual', description: 'A complete guide to navigating the complex world of healthcare compliance, including HIPAA and OIG work plans.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1622545198?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1622545198?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1622545198?tag=medical0f1-21'}},
    { id: 'book-em-coding', title: 'Evaluation and Management (E/M) Coding', description: 'Master the complexities of E/M coding with the latest 2024 guidelines and real-world case studies.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1640161408?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1640161408?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1640161408?tag=medical0f1-21'}},
    { id: 'book-outpatient', title: 'Outpatient CDI and Coding', description: 'Focuses on the unique challenges of clinical documentation improvement and coding in the outpatient setting.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1622544973?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1622544973?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1622544973?tag=medical0f1-21'}},
    { id: 'book-profee', title: 'Principles of Physician-Based Coding', description: 'A guide to professional fee coding, covering CPT, ICD-10-CM, and HCPCS for physician services.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1584268392?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1584268392?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1584268392?tag=medical0f1-21'}},
    { id: 'book-revenue-cycle', title: 'The Revenue Cycle Handbook', description: 'Explore the entire revenue cycle management process, from patient registration to final payment.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1119755492?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1119755492?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1119755492?tag=medical0f1-21'}},
    { id: 'book-pharma', title: 'Pharmaceutical and Medical Device Coding', description: 'A specialty guide for coding related to pharmaceuticals, biologics, and medical devices.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1622541311?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1622541311?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1622541311?tag=medical0f1-21'}},
    { id: 'book-dental', title: 'Dental Coding with Confidence', description: 'Master CDT codes for accurate dental billing and claim submission with this comprehensive guide.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/0323871404?tag=mykada-20', 'in': 'https://www.amazon.in/dp/0323871404?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/0323871404?tag=medical0f1-21'}},
    { id: 'book-informatics', title: 'Health Informatics: A Practical Approach', description: 'An introduction to health informatics, covering data standards, EHRs, and the role of data in healthcare.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1284222047?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1284222047?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1284222047?tag=medical0f1-21'}},
    { id: 'book-career', title: 'The Medical Coder\'s Career Guide', description: 'A guide to building a successful career in medical coding, from certification to specialization and management.', affiliateLinks: { 'com': 'https://www.amazon.com/dp/1622021172?tag=mykada-20', 'in': 'https://www.amazon.in/dp/1622021172?tag=httpcodingonl-21', 'ae': 'https://www.amazon.ae/dp/1622021172?tag=medical0f1-21'}},
];