import type { RecommendedBook } from '../types';

export const localSuggestedBooks: RecommendedBook[] = [
    { id: 'book-cpc-guide', title: 'Official CPC® Certification Study Guide', description: "AAPC's official CPC exam study guide — anatomy, medical terminology, ICD-10-CM, CPT, HCPCS, practice questions and exam tips.", affiliateLinks: { com: 'https://www.amazon.com/dp/1635278910?tag=mykada-20', in: 'https://www.amazon.in/dp/1635278910?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/1285427998?tag=medical0f1-21'}},
    { id: 'book-icd10-cm', title: "Buck's ICD-10-CM for Physicians 2026", description: "Physician-focused ICD-10-CM code manual with full-color illustrations, Netter's Anatomy, and detailed guidelines.", affiliateLinks: { com: 'https://www.amazon.com/dp/0443380783?tag=mykada-20', in: 'https://www.amazon.in/dp/0443380783?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/0443380783?tag=medical0f1-21'}},
    { id: 'book-cpt-pro', title: 'AMA CPT® Professional 2026', description: 'The official Current Procedural Terminology (CPT) codebook from the American Medical Association, essential for every coder.', affiliateLinks: { com: 'https://www.amazon.com/dp/1640163354?tag=mykada-20', in: 'https://www.amazon.in/dp/1640163354?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/1640163354?tag=medical0f1-21'}},
    { id: 'book-hcpcs-level2', title: 'HCPCS Level II Professional 2026', description: 'Comprehensive guide for HCPCS Level II codes used for supplies, equipment, and drugs administered by physicians.', affiliateLinks: { com: 'https://www.amazon.com/dp/1622029947?tag=mykada-20', in: 'https://www.amazon.in/dp/1622029947?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/1622029947?tag=medical0f1-21'}},
    { id: 'book-medical-billing', title: 'Medical Billing & Coding For Dummies', description: 'An easy-to-understand guide covering the basics of medical billing and coding, perfect for beginners.', affiliateLinks: { com: 'https://www.amazon.com/dp/1119750393?tag=mykada-20', in: 'https://www.amazon.in/dp/1119750393?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/1119750393?tag=medical0f1-21'}},
    { id: 'book-step-by-step', title: 'Step-by-Step Medical Coding, 2024 Edition', description: 'This guide provides a solid foundation with a practical approach to mastering medical coding concepts and applications.', affiliateLinks: { com: 'https://www.amazon.com/dp/0323930872?tag=mykada-20', in: 'https://www.amazon.in/dp/0323930872?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/0323930872?tag=medical0f1-21'}},
    { id: 'book-terminology-health', title: 'Medical Terminology for Health Professions', description: 'A comprehensive resource that simplifies learning complex medical terminology through a clear and logical approach.', affiliateLinks: { com: 'https://www.amazon.com/dp/0357770170?tag=mykada-20', in: 'https://www.amazon.in/dp/0357770170?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/0357770170?tag=medical0f1-21'}},
    { id: 'book-anatomy-dummies', title: 'Anatomy & Physiology For Dummies', description: 'Makes complex topics of anatomy and physiology accessible and easy to understand for students and aspiring professionals.', affiliateLinks: { com: 'https://www.amazon.com/dp/1119543037?tag=mykada-20', in: 'https://www.amazon.in/dp/1119543037?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/1119543037?tag=medical0f1-21'}},
    { id: 'book-coder-survival', title: "The Medical Biller/Coder's Survival Guide", description: 'An essential guide packed with tips, tools, and strategies to navigate the challenges of the medical billing and coding world.', affiliateLinks: { com: 'https://www.amazon.com/dp/0323694676?tag=mykada-20', in: 'https://www.amazon.in/dp/0323694676?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/0323694676?tag=medical0f1-21'}}
];
